version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.8.25-management-alpine
    container_name: 'rabbitmq'
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_email

  consumer:
    container_name: 'consumer'
    environment:
      - JWT_SECRET=${JWT_SECRET}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=consumer
    ports:
      - '8080:80'
    depends_on:
        - rabbitmq

  producer:
    container_name: 'sender'
    environment:
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - FROM_EMAIL=${FROM_EMAIL}
      - OAUTH_TOKEN_FILE_NAME=${OAUTH_TOKEN_FILE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=sender
    ports:
      - '8081:80'
    depends_on:
        - rabbitmq


networks:
  rabbitmq_email: